# kube2iam
## Configuration values for the kube2iam dependency
## ref: https://github.com/helm/charts/blob/master/stable/kube2iam/README.md
##
kube2iam:
  extraArgs:
    base-role-arn: arn:aws:iam::[AWS Account Number]:role/
  rbac:
    create: true

## Configuration values for the nginx-ingress dependency
## ref: https://github.com/helm/charts/blob/master/stable/nginx-ingress/README.md
##
nginx-ingress:
  controller:
    replicaCount: 2
    config:
      use-proxy-protocol: "true"
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  rbac:
    create: true

# AWS ALB Ingress Controller
## Configuration values for the aws-alb-ingress-controller dependency
## ref: https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/README.md
##
aws-alb-ingress-controller:
  clusterName: [AWS Cluster Name]
  autoDiscoverAwsRegion: true
  autoDiscoverAwsVpcID: true
  podAnnotations:
    iam.amazonaws.com/role: "arn:aws:iam::[AWS Account Number]:role/KubernetesALBControllerRole"
  image:
    repository: docker.io/amazon/aws-alb-ingress-controller
    tag: "v1.1.0"
    pullPolicy: Always